version: '3'
services:

  db:
    container_name: foodgram_db_postgres
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    container_name: foodgram_backend
    image: kirillkuz/foodgram_backend:latest
    env_file:
      - ../.env
    restart: always
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - db

  frontend:
    container_name: foodgram_frontend
    image: kirillkuz/foodgram_frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    container_name: foodgram_gateway
    image: kirillkuz/foodgram_gateway:latest
    ports:
      - "9080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  pg_data:
  static:
  media: