# Generated by Django 3.2.3 on 2024-02-25 13:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe_ingredient',
            new_name='Recipeingredient',
        ),
        migrations.RenameModel(
            old_name='Shopping_cart',
            new_name='Shoppingcart',
        ),
    ]
